---
- hosts: servers

  tasks:

  - name: Set authorized key took from file
    authorized_key:
      user: vagrant
      state: present
      key: "{{ lookup('file', '/Users/osiefart/.ssh/id_rsa.pub') }}"
